# Data Loading

Importing packages

In [147]:
import pandas as pd
import numpy as np

Loading data from Excel

In [148]:
# file_path = "data/assessment_dataset.xlsx"
file_path = "data/assessment_dataset.csv"

sales = pd.read_csv(file_path)

# sales.to_csv('data/assessment_dataset.csv', index=False)

Understanding Data

In [149]:
sales.shape

(500000, 19)

In [150]:
sales.head(n=10)

,TransactionID,CustomerID,TransactionDate,TransactionAmount,PaymentMethod,Quantity,DiscountPercent,City,StoreType,CustomerAge,CustomerGender,LoyaltyPoints,ProductName,Region,Returned,FeedbackScore,ShippingCost,DeliveryTimeDays,IsPromotional
0,1,16795.0,2022-01-01 00:00:00,1910.91,Cash,1,35.00,Kolkata,In-Store,32.0,Male,2043,T-Shirt,North,No,4,24.31,5,No
1,2,1860.0,2022-01-01 00:01:00,58590.27,Cash,1,9.51,Lucknow,Online,40.0,Other,8490,Sofa,West,No,2,1502.96,7,Yes
2,3,39158.0,2022-01-01 00:02:00,280.21,Debit Card,1,16.55,Lucknow,Online,52.0,Other,6328,Notebook,North,Yes,2,22.30,2,Yes
3,4,NaN,NaN,86485.63,UPI,1,9.53,Jaipur,In-Store,62.0,Other,1139,Laptop,North,No,4,461.38,7,No
4,5,12284.0,2022-01-01 00:04:00,385.89,Debit Card,22,0.98,Kolkata,Online,31.0,Female,66,Apple,North,No,1,14.44,1,Yes
5,6,7265.0,2022-01-01 00:05:00,450.40,Credit Card,2,43.81,Kolkata,Online,58.0,Female,1798,T-Shirt,North,No,5,36.76,3,Yes
6,7,17850.0,2022-01-01 00:06:00,58286.23,Cash,1,8.59,Jaipur,In-Store,58.0,Male,4754,Laptop,North,Yes,5,251.42,4,Yes
7,8,38194.0,2022-01-01 00:07:00,158.10,UPI,10,47.78,Pune,Online,73.0,Female,4987,Notebook,East,No,1,19.81,4,Yes
8,9,22962.0,2022-01-01 00:08:00,40999.26,UPI,1,13.73,Pune,Online,50.0,Male,6466,Laptop,East,No,3,112.96,5,No
9,10,48191.0,2022-01-01 00:09:00,74686.61,UPI,1,38.29,Ahmedabad,In-Store,58.0,Other,8475,Laptop,West,Yes,1,150.29,6,No

In [151]:
sales.dtypes

TransactionID          int64
CustomerID           float64
TransactionDate          str
TransactionAmount    float64
PaymentMethod            str
Quantity               int64
DiscountPercent      float64
City                     str
StoreType                str
CustomerAge          float64
CustomerGender           str
LoyaltyPoints          int64
ProductName              str
Region                   str
Returned                 str
FeedbackScore          int64
ShippingCost         float64
DeliveryTimeDays       int64
IsPromotional            str
dtype: object

Transforming Returned column data type to boolean

In [152]:
sales['Returned'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [153]:
return_mapping = {'Yes': True, 'No': False}
sales['Returned'] = sales['Returned'].map(return_mapping)

sales['Returned']

0         False
1         False
2          True
3         False
4         False
          ...
499995     True
499996    False
499997    False
499998     True
499999     True
Name: Returned, Length: 500000, dtype: bool

In [154]:
sales['IsPromotional'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

Transforming IsPromotional column data type to boolean

In [155]:
return_mapping = {'Yes': True, 'No': False}
sales['IsPromotional'] = sales['IsPromotional'].map(return_mapping)

sales['IsPromotional']

0         False
1          True
2          True
3         False
4          True
          ...
499995     True
499996    False
499997     True
499998    False
499999    False
Name: IsPromotional, Length: 500000, dtype: bool

In [156]:
sales['TransactionDate'] = pd.to_datetime(sales['TransactionDate'])
sales['TransactionDate']

0        2022-01-01 00:00:00
1        2022-01-01 00:01:00
2        2022-01-01 00:02:00
3                        NaT
4        2022-01-01 00:04:00
                 ...
499995   2022-12-14 05:15:00
499996   2022-12-14 05:16:00
499997   2022-12-14 05:17:00
499998   2022-12-14 05:18:00
499999   2022-12-14 05:19:00
Name: TransactionDate, Length: 500000, dtype: datetime64[us]

In [157]:
# Set the 'TransactionID' column as the index
sales.set_index('TransactionID', inplace=True)

Checking Null Values

In [158]:
sales.isna().sum()

CustomerID           50000
TransactionDate      50000
TransactionAmount        0
PaymentMethod        50000
Quantity                 0
DiscountPercent          0
City                     0
StoreType            50000
CustomerAge          50000
CustomerGender       50000
LoyaltyPoints            0
ProductName          50000
Region               42633
Returned                 0
FeedbackScore            0
ShippingCost             0
DeliveryTimeDays         0
IsPromotional            0
dtype: int64

In [159]:
sales.isna().sum(axis=1)

TransactionID
1         0
2         0
3         0
4         2
5         0
         ..
499996    0
499997    0
499998    0
499999    0
500000    0
Length: 500000, dtype: int64

In [160]:
sales.isna().sum().sum()

np.int64(392633)

Forward Filling TransactionDate column

In [161]:
# TODO: ffill for date here, because dates are in sorted and very short range, may be usefull for ML training over just droping it.

sales['TransactionDate'] = sales['TransactionDate'].ffill()
sales['TransactionDate'].isna().sum()

np.int64(0)

Dropping all rows with null

In [162]:
sales = sales.dropna()

sales.shape

(404962, 18)

In [163]:
sales.isna().sum()

CustomerID           0
TransactionDate      0
TransactionAmount    0
PaymentMethod        0
Quantity             0
DiscountPercent      0
City                 0
StoreType            0
CustomerAge          0
CustomerGender       0
LoyaltyPoints        0
ProductName          0
Region               0
Returned             0
FeedbackScore        0
ShippingCost         0
DeliveryTimeDays     0
IsPromotional        0
dtype: int64

Data Quality Checking

In [164]:
sales.duplicated().sum()

np.int64(0)

In [165]:
sales.index.duplicated().sum()

np.int64(0)

In [166]:
sales[(sales['CustomerAge'] < 0) | (sales['CustomerAge'] > 100)]

Empty DataFrame
Columns: [CustomerID, TransactionDate, TransactionAmount, PaymentMethod, Quantity, DiscountPercent, City, StoreType, CustomerAge, CustomerGender, LoyaltyPoints, ProductName, Region, Returned, FeedbackScore, ShippingCost, DeliveryTimeDays, IsPromotional]
Index: []

In [167]:
sales[sales['TransactionAmount'] < 0]

,CustomerID,TransactionDate,TransactionAmount,PaymentMethod,Quantity,DiscountPercent,City,StoreType,CustomerAge,CustomerGender,LoyaltyPoints,ProductName,Region,Returned,FeedbackScore,ShippingCost,DeliveryTimeDays,IsPromotional
TransactionID,,,,,,,,,,,,,,,,,,
36,12394.0,2022-01-01 00:35:00,-858.73,UPI,5,42.52,Lucknow,Online,68.0,Male,4736,T-Shirt,North,False,3,46.27,2,False
126,43530.0,2022-01-01 02:05:00,-892.63,UPI,1,42.22,Lucknow,Online,64.0,Female,6196,T-Shirt,North,False,5,54.84,4,True
381,36777.0,2022-01-01 06:20:00,-540.62,Debit Card,10,17.47,Hyderabad,Online,64.0,Other,4947,Apple,West,False,5,12.31,2,True
536,47247.0,2022-01-01 08:55:00,-37.24,UPI,8,24.26,Chennai,In-Store,53.0,Other,7232,Notebook,East,True,2,37.59,3,True
578,18506.0,2022-01-01 09:37:00,-238.64,UPI,4,49.15,Lucknow,Online,35.0,Female,6955,Notebook,South,False,3,39.27,3,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499486,40022.0,2022-12-13 20:45:00,-284.35,Credit Card,1,6.71,Hyderabad,In-Store,62.0,Male,9333,Laptop,East,True,4,134.38,3,False
499550,16817.0,2022-12-13 21:49:00,-547.21,Debit Card,1,15.54,Hyderabad,Online,70.0,Female,6794,Sofa,West,True,2,1851.67,9,True
499716,34598.0,2022-12-14 00:35:00,-934.47,UPI,1,38.12,Delhi,In-Store,68.0,Other,3433,Laptop,South,False,5,336.89,3,False
499768,33164.0,2022-12-14 01:27:00,-721.19,Debit Card,4,45.96,Lucknow,In-Store,56.0,Other,4763,T-Shirt,East,False,2,52.75,5,False
499986,42903.0,2022-12-14 05:05:00,-537.95,Debit Card,1,32.75,Hyderabad,In-Store,44.0,Female,9150,Sofa,South,True,1,1675.77,8,False

In [168]:
sales = sales[sales['TransactionAmount'] >= 0]

In [169]:
sales[(sales['DiscountPercent'] < 0) | (sales['DiscountPercent'] > 100)]

Empty DataFrame
Columns: [CustomerID, TransactionDate, TransactionAmount, PaymentMethod, Quantity, DiscountPercent, City, StoreType, CustomerAge, CustomerGender, LoyaltyPoints, ProductName, Region, Returned, FeedbackScore, ShippingCost, DeliveryTimeDays, IsPromotional]
Index: []

In [170]:
sales[sales['Quantity'] <= 0]

Empty DataFrame
Columns: [CustomerID, TransactionDate, TransactionAmount, PaymentMethod, Quantity, DiscountPercent, City, StoreType, CustomerAge, CustomerGender, LoyaltyPoints, ProductName, Region, Returned, FeedbackScore, ShippingCost, DeliveryTimeDays, IsPromotional]
Index: []

Loading: Writing Clean Data to CSV

In [171]:
sales.to_csv("data/clean_assessment_dataset.csv")

Loading: in SQL Server

In [172]:
import pandas as pd
from sqlalchemy import create_engine
import urllib

In [173]:
SERVER = "localhost"
DATABASE = "etl_practice_db"
DRIVER = "ODBC Driver 17 for SQL Server"

params = urllib.parse.quote_plus(
    f"DRIVER={{{DRIVER}}};SERVER={SERVER};DATABASE={DATABASE};Trusted_Connection=yes;TrustServerCertificate=yes"
)
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

In [175]:
sales.to_sql("clean_sales_data", con=engine, if_exists="replace")

27